In [2]:
print(1)

1


# 1. Numpy & Python

In [ ]:
import numpy as np
import time

# Python list
python_list = list(range(1000000))
start = time.time()
result = [x * 2 for x in python_list]
print(f"Python: {time.time() - start:.4f}s")

# NumPy array
numpy_array = np.arange(1000000)
start = time.time()
result = numpy_array * 2
print(f"NumPy: {time.time() - start:.4f}s")

Python: 0.0609s
NumPy: 0.0180s


# 2. Creating Lists

2.1 From Python Lists

In [8]:
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d) # [1 2 3 4 5]
print(type(arr1d)) # <class 'numpy.ndarray'>

# 2D array (matrix)
arr2d = np.array([[1, 2, 3],
 [4, 5, 6]])
print(arr2d)
# [[1 2 3]
# [4 5 6]]

# 3D array
arr3d = np.array([[[1, 2], [3, 4]],
 [[5, 6], [7, 8]]])
print(arr3d.shape) # (2, 2, 2)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 2, 2)


2.2 Built-in Array Creation Functions

In [10]:
# zeros - all zeros
zeros = np.zeros((3, 4))
print(zeros)
# [[0. 0. 0. 0.]
# [0. 0. 0. 0.]
# [0. 0. 0. 0.]]

# ones - all ones
ones = np.ones((2, 3))
print(ones)
# [[1. 1. 1.]
# [1. 1. 1.]]

# full - all same value
full = np.full((2, 3), 7)
print(full)
# [[7 7 7]
# [7 7 7]]

# empty - uninitialized (faster but random values)
empty = np.empty((2, 2))
# identity matrix
identity = np.eye(4)
print(identity)
# [[1. 0. 0. 0.]
# [0. 1. 0. 0.]
# [0. 0. 1. 0.]
# [0. 0. 0. 1.]]
# diagonal matrix
diag = np.diag([1, 2, 3, 4])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2.3 Sequence Generation

In [12]:
# arange - like range but returns array
arr = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
arr = np.arange(2, 10) # [2 3 4 5 6 7 8 9]
arr = np.arange(0, 10, 2) # [0 2 4 6 8]
arr = np.arange(10, 0, -1) # [10 9 8 7 6 5 4 3 2 1]
# linspace - evenly spaced numbers
arr = np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1. ]
arr = np.linspace(0, 10, 11) # [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10.]
# logspace - evenly spaced on log scale
arr = np.logspace(0, 3, 4) # [1. 10. 100. 1000.]

2.4 Random Arrays


In [14]:
# Set seed for reproducibility
np.random.seed(42)
# Random floats [0, 1)
rand = np.random.rand(3, 4)
# Random floats from standard normal distribution
randn = np.random.randn(3, 4)
# Random integers
randint = np.random.randint(0, 10, size=(3, 4))
# Random choice from array
choice = np.random.choice([1, 2, 3, 4, 5], size=10)
# Shuffle array
arr = np.arange(10)
np.random.shuffle(arr)
# Random sample from distributions
normal = np.random.normal(loc=0, scale=1, size=1000)
uniform = np.random.uniform(low=0, high=1, size=1000)

# 3. 3. Array Attributes

In [17]:
arr = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])
# Shape - dimensions
print(arr.shape) # (3, 4) - 3 rows, 4 columns
# Number of dimensions
print(arr.ndim) # 2
# Total elements
print(arr.size) # 12
# Data type
print(arr.dtype) # int64
# Item size in bytes
print(arr.itemsize) # 8

# Total bytes
print(arr.nbytes) # 96 (12 elements × 8 bytes)

(3, 4)
2
12
int32
4
48


In [18]:
# Specify dtype
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_complex = np.array([1, 2, 3], dtype=np.complex128)
arr_bool = np.array([1, 0, 1], dtype=np.bool_)
# Common dtypes
# int8, int16, int32, int64
# uint8, uint16, uint32, uint64
# float16, float32, float64
# complex64, complex128
# bool_
# Convert dtype
arr = np.array([1.5, 2.7, 3.9])
arr_int = arr.astype(np.int32) # [1 2 3]

# 4. Indexing and Slicing 

4.1 Basic Indexing

In [19]:
# 1D array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # 10 (first element)
print(arr[-1]) # 50 (last element)
print(arr[2]) # 30
# 2D array
arr2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print(arr2d[0, 0]) # 1 (row 0, col 0)
print(arr2d[1, 2]) # 6 (row 1, col 2)
print(arr2d[2, -1]) # 9 (row 2, last col)
# Alternative syntax
print(arr2d[0][0]) # 1 (works but slower)

10
50
30
1
6
9
1


4.2 Slicing

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Basic slicing [start:stop:step]
print(arr[2:7]) # [2 3 4 5 6]
print(arr[:5]) # [0 1 2 3 4]
print(arr[5:]) # [5 6 7 8 9]
print(arr[::2]) # [0 2 4 6 8]
print(arr[::-1]) # [9 8 7 6 5 4 3 2 1 0] (reverse)
# 2D slicing
arr2d = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])
print(arr2d[0, :]) # [1 2 3 4] - first row
print(arr2d[:, 0]) # [1 5 9] - first column
print(arr2d[0:2, 1:3]) # [[2 3] [6 7]] - submatrix
print(arr2d[::2, ::2]) # [[1 3] [9 11]] - every other

[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
[[ 1  3]
 [ 9 11]]


4.3 Boolean Indexing


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Create boolean mask
mask = arr > 5
print(mask) # [False False False False False True True True True True]
# Apply mask
print(arr[mask]) # [6 7 8 9 10]
# Shorthand
print(arr[arr > 5]) # [6 7 8 9 10]
print(arr[arr % 2 == 0]) # [2 4 6 8 10] - even numbers
# Multiple conditions
print(arr[(arr > 3) & (arr < 8)]) # [4 5 6 7]
print(arr[(arr < 3) | (arr > 8)]) # [1 2 9 10]
# Modify with boolean indexing
arr[arr > 5] = 0
print(arr) # [1 2 3 4 5 0 0 0 0 0]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[4 5 6 7]
[ 1  2  9 10]
[1 2 3 4 5 0 0 0 0 0]


4.4 Fancy Indexing

In [22]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
# Index with array of indices
indices = np.array([1, 3, 5, 7])
print(arr[indices]) # [20 40 60 80]
# 2D fancy indexing
arr2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Select specific elements
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
print(arr2d[rows, cols]) # [3 5 7] (diagonal from top-right)
# Select specific rows
print(arr2d[[0, 2]]) # [[1 2 3] [7 8 9]]


[20 40 60 80]
[3 5 7]
[[1 2 3]
 [7 8 9]]


# 5. Array Manipulation

5.1 Reshaping

In [23]:
arr = np.arange(12)
print(arr) # [ 0 1 2 3 4 5 6 7 8 9 10 11]
# Reshape
reshaped = arr.reshape(3, 4)
print(reshaped)
# [[ 0 1 2 3]
# [ 4 5 6 7]
# [ 8 9 10 11]]
# Use -1 for automatic dimension
reshaped = arr.reshape(3, -1) # (3, 4)
reshaped = arr.reshape(-1, 6) # (2, 6)
# Flatten - convert to 1D
flattened = reshaped.flatten() # Returns copy
raveled = reshaped.ravel() # Returns view (faster)
# Transpose
transposed = reshaped.T
print(transposed.shape) # (4, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(6, 2)


5.2 Stacking and Splitting


In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Vertical stack
vstack = np.vstack((a, b))
print(vstack)
# [[1 2]
# [3 4]
# [5 6]
# [7 8]]
# Horizontal stack
hstack = np.hstack((a, b))
print(hstack)
# [[1 2 5 6]
# [3 4 7 8]]
# Concatenate (general)
concat = np.concatenate((a, b), axis=0) # Same as vstack
concat = np.concatenate((a, b), axis=1) # Same as hstack
# Split
arr = np.arange(12).reshape(4, 3)
split = np.vsplit(arr, 2) # Split into 2 along rows
split = np.hsplit(arr, 3) # Split into 3 along columns
split = np.split(arr, 2, axis=0) # General split


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


5.3 Adding and Removing Elements


In [25]:
arr = np.array([1, 2, 3])
# Append
new_arr = np.append(arr, [4, 5, 6]) # [1 2 3 4 5 6]
# Insert
new_arr = np.insert(arr, 1, [10, 20]) # [1 10 20 2 3]
# Delete
new_arr = np.delete(arr, 1) # [1 3]
# Unique
arr = np.array([1, 2, 2, 3, 3, 3])
unique = np.unique(arr) # [1 2 3]
unique, counts = np.unique(arr, return_counts=True)

# Practice Exercise

Exercise 1.1: Array Creation

In [46]:
# Create the following arrays:
# 1. Array of 20 zeros
all_zero = np.zeros(20)
print(f"====== All zero array: {all_zero}")

# 2. 5x5 identity matrix
matrix = np.identity(5)
print(f"====== 5x5 identity matrix:\n{matrix}")

# 3. Array from 10 to 50 (step 5)
ten_to_fifty = np.arange(10, 51, 5)
print(f"====== 10 to 50 array: {ten_to_fifty}")

# 4. 4x4 array of random integers (0-100)
four_four = np.random.randint(0, 100, (4, 4))
print(f"====== 4x4 array:\n{four_four}")

# 5. 3x3 array with values from 1 to 9
three_three = np.arange(1, 10).reshape(3, 3)
print(f"====== 3x3 array:\n{three_three}")




====== All zero array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
====== 5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
====== 10 to 50 array: [10 15 20 25 30 35 40 45 50]
====== 4x4 array:
[[68 29 87 58]
 [66 74 44  3]
 [25 26 45 63]
 [90 50 49  5]]
====== 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 1.2: Indexing Practice

In [94]:
# Given:
arr = np.arange(1, 26).reshape(5, 5)
print(f"====== Array:\n{arr}")

# Extract:
# 1. Element at row 2, column 3
print(f"------ Element at row 2, column 3: {arr[1, 2]}")

# 2. Last row
print(f"------ Last row: {arr[-1, :]}")

# 3. First column
print(f"------ First column: {arr[:, 0]}")

# 4. Submatrix (rows 1-3, columns 2-4)
print(f"------ Submatrix (rows 1-3, columns 2-4):\n{arr[0:3, 1:4]}")

# 5. Diagonal elements
print(f"------ Diagonal elements (rows 1-3, columns 2-4): {np.diag(arr)}")


# 6. Elements greater than 15
greater_than_fifteen = arr[arr > 15]
# greater_than_fifteen = [x for x in arr.flatten() if x > 15]
print(f"------ Elements greater than 15:  {greater_than_fifteen}")


====== Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
------ Element at row 2, column 3: 8
------ Last row: [21 22 23 24 25]
------ First column: [ 1  6 11 16 21]
------ Submatrix (rows 1-3, columns 2-4):
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
------ Diagonal elements (rows 1-3, columns 2-4): [ 1  7 13 19 25]
------ Elements greater than 15:  [16 17 18 19 20 21 22 23 24 25]


Exercise 1.3: Checkerboard


In [96]:
# Create an 8x8 checkerboard pattern:
# [[0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# ...]
checker_board = np.zeros((8, 8), dtype=int)
checker_board[0::2, 1::2] = 1
checker_board[1::2, 0::2] = 1
print(f"Checker Board: \n{checker_board}")


Checker Board: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise 1.4: Array Manipulation

In [103]:
# 1. Create array 1-12, reshape to 3x4
arr = np.arange(1, 13).reshape(3, 4)
print(f"====== 3x4: {arr}")

# 2. Transpose it
arr_transpose = arr.T
print(f"====== Transpose: {arr_transpose}")

# 3. Flatten it
arr_flatten = arr.flatten()
print(f"====== Flatten: {arr_flatten}")

# 4. Split into 3 equal parts
arr_split = np.split(arr_flatten, 3)
print(f"====== Split into 3 equal parts: {arr_split}")

# 5. Stack them horizontally
arr_stacked = np.hstack(arr_split)
print(f"====== Stack them horizontally:\n{arr_stacked}")


====== 3x4: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
====== Transpose: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
====== Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
====== Split into 3 equal parts: [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
====== Stack them horizontally:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 2. Pandas Fundamentals

In [104]:
import pandas as pd
print(pd.__version__)

2.2.3


Exercise 3.1: Create DataFrames

In [110]:
# Create a DataFrame with:
# - 10 students
# - Columns: Name, Math, English, Physics scores (random 0-100)
data = {
    'Name': [f'Student {i+1}' for i in range(10)],
    'Math': np.random.randint(0, 101, 10),
    'English': np.random.randint(0, 101, 10),
    'Physics': np.random.randint(0, 101, 10)
}
df = pd.DataFrame(data)

# - Calculate total and average
df['Total'] = df[['Math', 'English', 'Physics']].sum(axis=1)
df['Average'] = df[['Math', 'English', 'Physics']].mean(axis=1).round(2)

# - Find students with average > 80
top_students = df[df['Average'] > 80]

# 3. Tìm học sinh có điểm trung bình > 80
print("--- Danh sách học sinh ---")
print(df)
print("\n--- Học sinh xuất sắc (Average > 80) ---")
print(top_students)


--- Danh sách học sinh ---
         Name  Math  English  Physics  Total  Average
0   Student 1    14       23       70    107    35.67
1   Student 2    71       25        8    104    34.67
2   Student 3    77       88       87    252    84.00
3   Student 4    86       59        0    145    48.33
4   Student 5    61       40        7    108    36.00
5   Student 6    39       28       87    154    51.33
6   Student 7    84       14       62    160    53.33
7   Student 8    79       44       10    133    44.33
8   Student 9    81       64       80    225    75.00
9  Student 10    52       88        7    147    49.00

--- Học sinh xuất sắc (Average > 80) ---
        Name  Math  English  Physics  Total  Average
2  Student 3    77       88       87    252     84.0


Exercise 3.2: Read and Explore

In [119]:
# Download Titanic dataset from Kaggle or use:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
print(df)
# Answer:
# 1. How many rows and columns?
rows, cols = df.shape
print(f"====== Rows: {rows}, Columns: {cols}")

# 2. What are the column names and types?
print("====== Column names and types:")
print(df.dtypes)

# 3. How many missing values per column?
print("====== Missing values per column:")
print(df.isnull().sum())

# 4. What is the survival rate?
print("====== Survival rate:")
print(df['Survived'].mean())

# 5. Average age of passengers?
print("====== Average age of passengers:")
print(df['Age'].mean())

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 