## Exercise 2.1: Broadcasting Practice

In [1]:
# Create a 5x5 distance matrix where element [i,j]
# is the absolute difference |i - j|
# Expected:
# [[0 1 2 3 4]
# [1 0 1 2 3]
# [2 1 0 1 2]
# [3 2 1 0 1]
# [4 3 2 1 0]]
import numpy as np

n = 5

# Create array [0,1,2,3,4]
arr = np.arange(n)

# Compute distance matrix
dist_matrix = np.abs(arr[:, None] - arr)

print(dist_matrix)

[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 0 1]
 [4 3 2 1 0]]


## Exercise 2.2: Statistics

In [2]:
# Given: 100 random exam scores (0-100)
scores = np.random.randint(0, 101, 100)
# Calculate:
# 1. Mean, median, std
# 2. Number of students who passed (≥50)
# 3. Percentage of A grades (≥90)
# 4. Grade distribution (A, B, C, D, F)

import numpy as np

np.random.seed(42)

# Given data
scores = np.random.randint(0, 101, 100)

# 1. Mean, median, std
mean_score = np.mean(scores)
median_score = np.median(scores)
std_score = np.std(scores)

print("Mean:", mean_score)
print("Median:", median_score)
print("Std Dev:", std_score)

# 2. Number of students who passed (≥50)
passed = np.sum(scores >= 50)
print("Passed:", passed)

# 3. Percentage of A grades (≥90)
a_percentage = np.mean(scores >= 90) * 100
print("A grade %:", a_percentage)

# 4. Grade distribution
grades = {
    "A": np.sum(scores >= 90),
    "B": np.sum((scores >= 80) & (scores < 90)),
    "C": np.sum((scores >= 70) & (scores < 80)),
    "D": np.sum((scores >= 60) & (scores < 70)),
    "F": np.sum(scores < 60)
}

print("Grade distribution:", grades)

Mean: 51.31
Median: 53.5
Std Dev: 29.555268565858103
Passed: 58
A grade %: 9.0
Grade distribution: {'A': np.int64(9), 'B': np.int64(13), 'C': np.int64(12), 'D': np.int64(9), 'F': np.int64(57)}


## Exercise 2.3: Linear Algebra

In [4]:
# 1. Solve the system:
# x + 2y + 3z = 14
# 2x + 5y + 3z = 18
# 4x + 6y + 8z = 32
# 2. Find eigenvalues of:
# [[4, -2],
# [1, 1]]

import numpy as np

# Coefficient matrix A
A = np.array([
    [1, 2, 3],
    [2, 5, 3],
    [4, 6, 8]
])

# Right-hand side vector b
b = np.array([14, 18, 32])

# Solve Ax = b
solution = np.linalg.solve(A, b)

print("Solution (x, y, z):", solution)

# Matrix
M = np.array([
    [4, -2],
    [1, 1]
])

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(M)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Solution (x, y, z): [-5.6  3.2  4.4]
Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## Exercise 2.4: Image Processing Simulation

In [10]:
# Create a 100x100 "image" (random values 0-255)
import numpy as np

np.random.seed(42)

img = np.random.randint(0, 256, (100, 100))
print(img.shape)
# 1. Normalize to 0-1 range
img_norm = img / 255.0
# 2. Apply threshold (>0.5 = 1, else 0)
binary_img = (img_norm > 0.5).astype(int)
# 3. Count white and black pixels
binary_img = (img_norm > 0.5).astype(int)
# 4. Calculate mean intensity per row
white_pixels = np.sum(binary_img == 1)
black_pixels = np.sum(binary_img == 0)

print("White pixels:", white_pixels)
print("Black pixels:", black_pixels)

# 5. Calculate mean intensity per row
mean_intensity_per_row = np.mean(img_norm, axis=1)
print("Mean intensity per row:", mean_intensity_per_row)
print("==================================")
print(mean_intensity_per_row[:10])  # first 10 rows




(100, 100)
White pixels: 5031
Black pixels: 4969
Mean intensity per row: [0.49066667 0.52486275 0.53729412 0.56462745 0.50811765 0.48698039
 0.51960784 0.52321569 0.51219608 0.52152941 0.51811765 0.51854902
 0.44717647 0.46929412 0.43592157 0.49823529 0.49019608 0.51196078
 0.48588235 0.51572549 0.50729412 0.51721569 0.46011765 0.52835294
 0.45760784 0.52301961 0.4534902  0.46494118 0.52592157 0.49431373
 0.45666667 0.49956863 0.47301961 0.50329412 0.51662745 0.55078431
 0.51090196 0.49407843 0.50615686 0.49345098 0.542      0.46298039
 0.51152941 0.51968627 0.51007843 0.47568627 0.48521569 0.47427451
 0.49980392 0.54984314 0.45180392 0.45627451 0.50058824 0.46568627
 0.53568627 0.49909804 0.50380392 0.49639216 0.52741176 0.49384314
 0.48956863 0.43937255 0.49937255 0.47921569 0.57858824 0.47466667
 0.49819608 0.51847059 0.52333333 0.51847059 0.44890196 0.53729412
 0.55537255 0.54529412 0.53247059 0.55098039 0.52819608 0.532
 0.51078431 0.50607843 0.44741176 0.4707451  0.50470588 0.517